### ISSUE TITLE
What architecture is the model using?

### ISSUE THREAD

**Issue by maybeluo** [Russell91/nlpcaffe#1]
I'm wondering the model behind your demo, could give some description or the paper related? Thanks

**Comment by Russell91** [comment]
The model is motivated by the decoder portion of Google's recent encoder decoder work [1]. The data set is taken from the first 300k sentences of the Billion Word Corpus [2].

The model first takes each word of a sentence and grabs the corresponding word vector with the wordvec layer. These word vectors are then fed into the two tiers of LSTM layers, vertically separated by drop out layers. The output of the second dropout layer is then fed into a softmax for prediction of the index of the next word. Here is Caffe's rendering of the model when the max sentence length is set to 3:

<img src="http://russellsstewart.com/s/lm/model.jpg"></img>

[1] http://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf
[2] http://static.googleusercontent.com/media/research.google.com/en/us/pubs/archive/41880.pdf

**Comment by maybeluo** [comment]
Thanks.

**Comment by Russell91** [comment]
I'm actually going to leave this open for the time being in case others have the same question.

**Comment by deeplearningmachine** [comment]
Hi Russell,

From your description above, the only difference of your model, compared to Google's decoder, is the initial state. In Google's approach, the initial state v is a fixed vector which summarizes the source sentence, but here you don't have the v. 

Does I understand your model correctly?

Thanks in advance.

-DLM
