### ISSUE TITLE
how to use the trained model to generate text

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/nlpcaffe#10]
Hi Russell,

I just wonder if the trained language model in your installed example can be used to generate text? and how I could do so in Caffe?

Thanks a lot!

**Comment by Russell91** [comment]
I stopped development of NlpCaffe before this type of functionality was available. My most recent work has been on ApolloCaffe, which has an example of a CharRNN for text generation that you may want to check out:

https://github.com/Russell91/apollocaffe/tree/master/examples/apollocaffe/char_model

**Comment by deeplearningmachine** [comment]
Hi Russell,

Thanks for the reply. I will take a look at apollocaffe.

-DLM
