### ISSUE TITLE
How to integrate new features from latest caffe

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/nlpcaffe#11]
Hi,

Would it be possible to incorporate new features from the latest caffe? I am particularly interested in the "repeated bool propagate_down = 11" parameter in the layers. I wonder if there is a easy way to use it in the caffe_NLP?

Thank you in advance.

-DLM

**Comment by Russell91** [comment]
You could always try to merge that feature in yourself, but it might be somewhat difficult. I do have another repository, http://github.com/Russell91/apollocaffe that contains many of the features of NLPCaffe and runs against a much more recent Caffe version. There is an example of a character level language model [here](https://github.com/Russell91/apollocaffe/tree/master/examples/apollocaffe/char_model), for example. I'm afraid that's about all I can do to help.

**Comment by deeplearningmachine** [comment]
Thanks a lot, Russell, for your quick response and the pointer!

-DLM
