### ISSUE TITLE
Pre-trained word vector

### ISSUE THREAD

**Issue by deeplearningmachine** [Russell91/nlpcaffe#15]
Hi Russell,

I just wonder if I can load pre-trained vectors such as those generated with Word2Vec, instead of initialize them randomly, in the wordVector layer?

Thanks in advance,

-DLM

**Comment by Russell91** [comment]
This would unfortunately be somewhat difficult. You would need to get the wordvectors into the .caffemodel binary format in a layer of the same name that you would eventually use. If you look into that format, you would be able to make this work though.

**Comment by deeplearningmachine** [comment]
Thanks a lot; I will look into that format!

-DLM
