### ISSUE TITLE
Do transpose though Reshape method

### ISSUE THREAD

**Issue by DogNick** [Russell91/nlpcaffe#18]
Hi Russell,

I noticed that  in the Blob::Reshape() method,  what is performed is just the resize of the shape(dimensions configuration) and some memory allocation if nessesary, but the row - colomn order  in memory remains unchanged.  Now i gonna do a Transpose operation on my input (N,C,H,1) into 
(N,H,C,1) ,  say, each matrix of C*H should be transposed into H*C ,  it seems that i cannot just do the reshape() for the Row-Major principle . Do i really have to just create a buffer blob to make a handcrafted copy issure ? 

Or if i ignored something in the srource code that could be an explaination itself , it'll be very kind of you to tell me.  Many Many Thanks !

**Comment by Russell91** [comment]
Yes, you need to either create a buffer or do an in-place transpose operation. If you need to do this very quickly, I actually wrote a high level caffe_cpu_transpose and caffe_gpu_transpose operation that you can find here: https://github.com/Russell91/apollocaffe/blob/master/src/caffe/util/math_functions.cpp

**Comment by DogNick** [comment]
Ah sorry , I just cannot locate the code of caffe_cpu_transpose() , would you please specify it for me ?
and I also found that functions in the math_function.cpp seems not to take into consideration of numerical stability, For example , i want to do some consecutive matrix multiplication just like those taken in forward-backword alogorithm(computation of alpha,beta matrix and so on), elements of matrix is often referred as a log probability, in which situation, the multiplication is transferred to addition and vector dot operation is transferred to a logSumExp operation with max-value trick involved. Since I learned that functions in the math_function.cpp are based on more basic cblas functions with many probable optimization which is unknown for me, I wonder whether i could make such a numerical-stable version of those functions just by handling element roughly with possible little efficiency loss? 
Sorry for bothering you all the time ....   - -!

**Comment by Russell91** [comment]
Apologies, the transpose code is for the gpu only (see caffe_gpu_transpose):
https://github.com/Russell91/apollocaffe/blob/master/src/caffe/util/math_functions.cu

For the cpu, it looks like I was just doing it manually.

**Comment by DogNick** [comment]
Many thanks for the code Russell !,  
and what about the........ second question ?????  ^-^

**Comment by DogNick** [comment]
What's your advice about the "LogSumExp"  implementation of matrix multiplication ? Is there any efficient way of doing this ? (may use some cblas functions ?)

**Comment by Russell91** [comment]
Unfortunately, that question is just off topic for this github issues section, as it doesn't really involve understanding Caffe or the nlpcaffe API so much as help with writing some generic c++ code. I wish you the best of luck on solving it though!

**Comment by DogNick** [comment]
Many thanks !
