### ISSUE TITLE
can not download the data for the model 

### ISSUE THREAD

**Issue by wenqf11** [Russell91/nlpcaffe#19]
Hi Russell,

I follow ReadMe Example
```Bash
./data/language_model/get_lm.sh
```
but I can not  download data, is there any problem with your website? or because i am constrained by GFW, could you please send me (qingfu.wen@gmail.com) those four files?

thanks
Qingfu

**Comment by Russell91** [comment]
Yes, I had some website downtime today in the process of transferring the
registrar for the domain. It should be fixed now though! Sorry for the
inconvenience.

**Comment by wenqf11** [comment]
OK, thanks a lot.

**Comment by wenqf11** [comment]
sorry to bother you again, after I execute python ./examples/language_model/create_lm.py --make_data,  I got this error:
python ./examples/language_model/create_lm.py --make_data
Starting train
Writing 306068 sentences
Starting valid
Writing 3000 sentences
Starting test
Writing 3000 sentences
Traceback (most recent call last):
  File "./examples/language_model/create_lm.py", line 336, in <module>
    main()
  File "./examples/language_model/create_lm.py", line 333, in main
    prepare(get_base_param())
  File "./examples/language_model/create_lm.py", line 325, in prepare
    write_net(param)
  File "./examples/language_model/create_lm.py", line 270, in write_net
    f.write(str(get_net(param, deploy=False, batch_size = param['train_batch_size'])))
  File "./examples/language_model/create_lm.py", line 131, in get_net
    wordvec_layer.wordvec_param.dimension = param['wordvec_length']
AttributeError: 'LayerParameter' object has no attribute 'wordvec_param'

Is this a version problem of something?

**Comment by wenqf11** [comment]
this is because i got a caffe maked, didn't make caffe first. so I copied 'caff_pb2.py' from 'python/caffe/proto' to 'example/language_model/', when execute
```Python
import caffe_pb2
```
it will use this 'caffe_pb2.py'
