### ISSUE TITLE
cuDNN v4

### ISSUE THREAD

**Issue by yusukenaito** [Russell91/nlpcaffe#25]
nVIDIA released cuDNN v4 in Feb 2016. In spite of normal installation of caffe, nlpcaffe have compile error like
[error.txt](https://github.com/Russell91/nlpcaffe/files/181193/error.txt)

I think the all header's may be replaced cudnnTensor4dDescriptor_t as cudnnTensorDescriptor_t.
However errors remains
[error2.txt](https://github.com/Russell91/nlpcaffe/files/181194/error2.txt)

Does anybody resolved this?

**Comment by Russell91** [comment]
@yusukenaito I spent a few hours today to upgrade nlpcaffe to the April 2016 caffe. See the dev branch at https://github.com/Russell91/nlpcaffe/tree/dev. Please let me know if this works for you.

**Comment by yusukenaito** [comment]
Hi, Thanks so much!
I could complete language_model example until train today.
My environment is
CPU: Core i7-3770 3.5Ghz
GPU: Geforce GTX 780
OS: ubuntu 14.04 LTS
CUDA 7.5-18
cuDNN: v4

Sincerely Yours
Yusuke Naito
