### ISSUE TITLE
I do not why ，the data for language_model/get_lm.sh can not be downloaded?

### ISSUE THREAD

**Issue by zanghao2** [Russell91/nlpcaffe#30]

**Comment by xiequnyi** [comment]
Hi Russell,

I follow ReadMe Example

./data/language_model/get_lm.sh
but I can not download data, is there any problem with your website? 
could you please send me (qunyi_xie@163.com) those four files?

thanks
Qunyi Xie

**Comment by xiequnyi** [comment]
@Russell91

**Comment by huangyaling** [comment]
I have the same problem.

**Comment by douzsh** [comment]
Can anyone share the data now?
