### ISSUE TITLE
typo : should be 'python examples/language_model/create_lm.py --make_data'

### ISSUE THREAD

**Issue by andyyuan78** [Russell91/nlpcaffe#6]

**Comment by Russell91** [comment]
Are you suggesting to remove the `./`? Is that not working for you?

**Comment by andyyuan78** [comment]
python ./examples/launguage_model/create_lm.py --make_data
----should be 'language_model'

**Comment by Russell91** [comment]
Oh thanks. I really couldn't figure out what had changed!
