### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by andyyuan78** [Russell91/nlpcaffe#7]
ubgpu@ubgpu:~/github/nlp_caffe$ git clone https://github.com/Russell91/nlpcaffe.git
Cloning into 'nlpcaffe'...
remote: Counting objects: 20426, done.
remote: Total 20426 (delta 0), reused 0 (delta 0), pack-reused 20426
Receiving objects: 100% (20426/20426), 29.63 MiB | 3.36 MiB/s, done.
Resolving deltas: 100% (13401/13401), done.
Checking connectivity... done.
ubgpu@ubgpu:~/github/nlp_caffe$ 

ubgpu@ubgpu:~/github/nlp_caffe$ cd nlpcaffe/
ubgpu@ubgpu:~/github/nlp_caffe/nlpcaffe$ make
Makefile:4: Makefile.config: No such file or directory
make: *** No rule to make target `Makefile.config'.  Stop.

**Comment by Russell91** [comment]
Please check out the installation for caffe first at http://caffe.berkeleyvision.org/installation.html. The process is nontrivial and you'll get much better Google support for the main Caffe branch. Once, you do that, you can use the same Makefile.config. If you have successfully installed Caffe, and you can't install this fork, please post any issues that you're having.

**Comment by andyyuan78** [comment]
I had misunderstood the install step.

now it works well

**Comment by Russell91** [comment]
No problem. Good luck using the library now that you've got it installed. If you're willing to share, I'd be interested to hear what you're hoping to accomplish. I haven't really communicated with other users before.
