### ISSUE TITLE
where is the input words in your create_lm.py?

### ISSUE THREAD

**Issue by imaglib** [Russell91/nlpcaffe#9]
hi Russell, I found the input_words and target_words both use same input line in your code. If i use my own data , I can change the first loop to add input words ,right?
                
    for j in range(param['maximum_length']):
         if j == 0:
               datum.float_data.append(param['start_symbol'])
         else:
               datum.float_data.append(target_line[j - 1])
    for j in range(param['maximum_length']):
         datum.float_data.append(target_line[j])

**Comment by Russell91** [comment]
I'm not sure exactly what you're asking, but I think the answer is yes. You can modify those lines to encode any float data you want into the arrays. Just make sure they are still the same length.

**Comment by imaglib** [comment]
The first loop append the input words data , the seond append target words, right? I think they are should from different source data, for example , inputs  are from English sentence and the targets are from France sentence. But the input data and the target data are both from target_line. is it ok?

**Comment by Russell91** [comment]
Yea, so this code just creates a protobuf array, and you can put whatever sort of numbers you want to in there. The first for loop will fill the inputs to the network at each step, and the second for loop will fill the trained predictions. It might be difficult to get translation to work this way, but it would be very cool if it did!

**Comment by imaglib** [comment]
Thanks , I want to use it to train a sentence to sentence model, for example QA model , is it work? Do you have any other ideas?

**Comment by Russell91** [comment]
Yea, so NLP-Caffe was originally designed for sequence to sequence, but that code was removed before publishing because it was kind of a kludge. If you are interested in doing this, and you don't mind moving away from Caffe, you might check out my new library <a href="apollo.deepmatter.io">Apollo<a>
